// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/auth/sign_in/data/repository_imp/auth_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/features/auth/sign_in/data/data_source/auth_local_data_source.dart'
    as _i6;
import 'package:fitness_app/features/auth/sign_in/data/data_source/auth_remote_data_source.dart'
    as _i3;
import 'package:fitness_app/features/auth/sign_in/data/model/sign_in_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/sign_in/domain/entity/sign_in_request.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInDTO_0 extends _i1.SmartFake implements _i2.SignInDTO {
  _FakeSignInDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SignInDTO> signIn(_i5.SignInRequest? data) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [data]),
            returnValue: _i4.Future<_i2.SignInDTO>.value(
              _FakeSignInDTO_0(this, Invocation.method(#signIn, [data])),
            ),
          )
          as _i4.Future<_i2.SignInDTO>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#saveEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
