// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/auth/forget_password/data/data_source/create_new_password_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:fitness_app/core/api/api_client.dart' as _i11;
import 'package:fitness_app/features/auth/change_password/date/model/change_password_model.dart'
    as _i4;
import 'package:fitness_app/features/auth/change_password/date/model/change_password_request_model.dart'
    as _i18;
import 'package:fitness_app/features/auth/forget_password/data/models/create_new_passwordrequset.dart'
    as _i17;
import 'package:fitness_app/features/auth/forget_password/data/models/forget_password_request.dart'
    as _i14;
import 'package:fitness_app/features/auth/forget_password/data/models/verify_reset_code_request.dart'
    as _i15;
import 'package:fitness_app/features/auth/sign_in/data/model/sign_in_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/sign_in/domain/entity/sign_in_request.dart'
    as _i13;
import 'package:fitness_app/features/auth/sign_up/data/models/signup_request_model.dart'
    as _i16;
import 'package:fitness_app/features/auth/sign_up/data/models/signup_response_model.dart'
    as _i3;
import 'package:fitness_app/features/Exercise/data/model/exercise_dto.dart'
    as _i9;
import 'package:fitness_app/features/Exercise/data/model/levels_response_dto.dart'
    as _i10;
import 'package:fitness_app/features/home/data/model/exercise_response_dto.dart'
    as _i8;
import 'package:fitness_app/features/meals_categories/data/models/meal_categories_model.dart'
    as _i5;
import 'package:fitness_app/features/worksout/data/model/muscles_data_response_model.dart'
    as _i7;
import 'package:fitness_app/features/worksout/data/model/muscles_tab_response_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInDTO_0 extends _i1.SmartFake implements _i2.SignInDTO {
  _FakeSignInDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponseModel_1 extends _i1.SmartFake
    implements _i3.SignupResponseModel {
  _FakeSignupResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordModel_2 extends _i1.SmartFake
    implements _i4.ChangePasswordModel {
  _FakeChangePasswordModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealCategoriesModel_3 extends _i1.SmartFake
    implements _i5.MealCategoriesModel {
  _FakeMealCategoriesModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesTabResponseModel_4 extends _i1.SmartFake
    implements _i6.MusclesTabResponseModel {
  _FakeMusclesTabResponseModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesDataResponseModel_5 extends _i1.SmartFake
    implements _i7.MusclesDataResponseModel {
  _FakeMusclesDataResponseModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercisesResponseDTO_6 extends _i1.SmartFake
    implements _i8.ExercisesResponseDTO {
  _FakeExercisesResponseDTO_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseResponseDTO_7 extends _i1.SmartFake
    implements _i9.ExerciseResponseDTO {
  _FakeExerciseResponseDTO_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevelsResponseDTO_8 extends _i1.SmartFake
    implements _i10.LevelsResponseDTO {
  _FakeLevelsResponseDTO_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i11.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.SignInDTO> signIn(_i13.SignInRequest? data) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [data]),
            returnValue: _i12.Future<_i2.SignInDTO>.value(
              _FakeSignInDTO_0(this, Invocation.method(#signIn, [data])),
            ),
          )
          as _i12.Future<_i2.SignInDTO>);

  @override
  _i12.Future<void> forgotPassword(_i14.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> verifyResetCode(_i15.VerifyResetCodeRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.SignupResponseModel> signup(_i16.SignupRequestModel? body) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [body]),
            returnValue: _i12.Future<_i3.SignupResponseModel>.value(
              _FakeSignupResponseModel_1(
                this,
                Invocation.method(#signup, [body]),
              ),
            ),
          )
          as _i12.Future<_i3.SignupResponseModel>);

  @override
  _i12.Future<void> createNewPassword(_i17.CreateNewPasswordrequset? request) =>
      (super.noSuchMethod(
            Invocation.method(#createNewPassword, [request]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.ChangePasswordModel> changePassword(
    _i18.ChangePasswordRequestModel? data,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [data, token]),
            returnValue: _i12.Future<_i4.ChangePasswordModel>.value(
              _FakeChangePasswordModel_2(
                this,
                Invocation.method(#changePassword, [data, token]),
              ),
            ),
          )
          as _i12.Future<_i4.ChangePasswordModel>);

  @override
  _i12.Future<_i5.MealCategoriesModel> getMealsCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getMealsCategories, []),
            returnValue: _i12.Future<_i5.MealCategoriesModel>.value(
              _FakeMealCategoriesModel_3(
                this,
                Invocation.method(#getMealsCategories, []),
              ),
            ),
          )
          as _i12.Future<_i5.MealCategoriesModel>);

  @override
  _i12.Future<_i6.MusclesTabResponseModel> getMusclesTabs() =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesTabs, []),
            returnValue: _i12.Future<_i6.MusclesTabResponseModel>.value(
              _FakeMusclesTabResponseModel_4(
                this,
                Invocation.method(#getMusclesTabs, []),
              ),
            ),
          )
          as _i12.Future<_i6.MusclesTabResponseModel>);

  @override
  _i12.Future<_i7.MusclesDataResponseModel> getMusclesData(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesData, [id]),
            returnValue: _i12.Future<_i7.MusclesDataResponseModel>.value(
              _FakeMusclesDataResponseModel_5(
                this,
                Invocation.method(#getMusclesData, [id]),
              ),
            ),
          )
          as _i12.Future<_i7.MusclesDataResponseModel>);

  @override
  _i12.Future<_i8.ExercisesResponseDTO> getAllExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, []),
            returnValue: _i12.Future<_i8.ExercisesResponseDTO>.value(
              _FakeExercisesResponseDTO_6(
                this,
                Invocation.method(#getAllExercises, []),
              ),
            ),
          )
          as _i12.Future<_i8.ExercisesResponseDTO>);

  @override
  _i12.Future<_i9.ExerciseResponseDTO> getExercisesByMuscleAndDifficulty(
    String? muscleId,
    String? difficultyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByMuscleAndDifficulty, [
              muscleId,
              difficultyId,
            ]),
            returnValue: _i12.Future<_i9.ExerciseResponseDTO>.value(
              _FakeExerciseResponseDTO_7(
                this,
                Invocation.method(#getExercisesByMuscleAndDifficulty, [
                  muscleId,
                  difficultyId,
                ]),
              ),
            ),
          )
          as _i12.Future<_i9.ExerciseResponseDTO>);

  @override
  _i12.Future<_i8.ExercisesResponseDTO> getRecommendExercises(
    String? targetMuscleGroupId,
    String? difficultyLevelId,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendExercises, [
              targetMuscleGroupId,
              difficultyLevelId,
              limit,
            ]),
            returnValue: _i12.Future<_i8.ExercisesResponseDTO>.value(
              _FakeExercisesResponseDTO_6(
                this,
                Invocation.method(#getRecommendExercises, [
                  targetMuscleGroupId,
                  difficultyLevelId,
                  limit,
                ]),
              ),
            ),
          )
          as _i12.Future<_i8.ExercisesResponseDTO>);

  @override
  _i12.Future<_i10.LevelsResponseDTO> getLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getLevels, []),
            returnValue: _i12.Future<_i10.LevelsResponseDTO>.value(
              _FakeLevelsResponseDTO_8(this, Invocation.method(#getLevels, [])),
            ),
          )
          as _i12.Future<_i10.LevelsResponseDTO>);
}
