// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/Exercise/data/data_source/exercise_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:fitness_app/core/api/api_client.dart' as _i6;
import 'package:fitness_app/features/auth/forget_password/data/models/create_new_passwordrequset.dart'
    as _i12;
import 'package:fitness_app/features/auth/forget_password/data/models/forget_password_request.dart'
    as _i9;
import 'package:fitness_app/features/auth/forget_password/data/models/verify_reset_code_request.dart'
    as _i10;
import 'package:fitness_app/features/auth/sign_in/data/model/sign_in_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/sign_in/domain/entity/sign_in_request.dart'
    as _i8;
import 'package:fitness_app/features/auth/sign_up/data/models/signup_request_model.dart'
    as _i11;
import 'package:fitness_app/features/auth/sign_up/data/models/signup_response_model.dart'
    as _i3;
import 'package:fitness_app/features/Exercise/data/model/exercise_dto.dart'
    as _i4;
import 'package:fitness_app/features/Exercise/data/model/levels_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInDTO_0 extends _i1.SmartFake implements _i2.SignInDTO {
  _FakeSignInDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponseModel_1 extends _i1.SmartFake
    implements _i3.SignupResponseModel {
  _FakeSignupResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseResponseDTO_2 extends _i1.SmartFake
    implements _i4.ExerciseResponseDTO {
  _FakeExerciseResponseDTO_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevelsResponseDTO_3 extends _i1.SmartFake
    implements _i5.LevelsResponseDTO {
  _FakeLevelsResponseDTO_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.SignInDTO> signIn(_i8.SignInRequest? data) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [data]),
            returnValue: _i7.Future<_i2.SignInDTO>.value(
              _FakeSignInDTO_0(this, Invocation.method(#signIn, [data])),
            ),
          )
          as _i7.Future<_i2.SignInDTO>);

  @override
  _i7.Future<void> forgotPassword(_i9.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyResetCode(_i10.VerifyResetCodeRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.SignupResponseModel> signup(_i11.SignupRequestModel? body) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [body]),
            returnValue: _i7.Future<_i3.SignupResponseModel>.value(
              _FakeSignupResponseModel_1(
                this,
                Invocation.method(#signup, [body]),
              ),
            ),
          )
          as _i7.Future<_i3.SignupResponseModel>);

  @override
  _i7.Future<void> createNewPassword(_i12.CreateNewPasswordrequset? request) =>
      (super.noSuchMethod(
            Invocation.method(#createNewPassword, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.ExerciseResponseDTO> getExercisesByMuscleAndDifficulty(
    String? muscleId,
    String? difficultyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByMuscleAndDifficulty, [
              muscleId,
              difficultyId,
            ]),
            returnValue: _i7.Future<_i4.ExerciseResponseDTO>.value(
              _FakeExerciseResponseDTO_2(
                this,
                Invocation.method(#getExercisesByMuscleAndDifficulty, [
                  muscleId,
                  difficultyId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.ExerciseResponseDTO>);

  @override
  _i7.Future<_i5.LevelsResponseDTO> getLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getLevels, []),
            returnValue: _i7.Future<_i5.LevelsResponseDTO>.value(
              _FakeLevelsResponseDTO_3(this, Invocation.method(#getLevels, [])),
            ),
          )
          as _i7.Future<_i5.LevelsResponseDTO>);
}
