// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/meals_categories/data/data_source/get_meals_by_category_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fitness_app/core/api/meals_api_client.dart' as _i4;
import 'package:fitness_app/features/meals_categories/data/models/meal_categories_reponse.dart'
    as _i2;
import 'package:fitness_app/features/meals_categories/data/models/meals_by_category_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealCategoriesReponse_0 extends _i1.SmartFake
    implements _i2.MealCategoriesReponse {
  _FakeMealCategoriesReponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealsByCategoryResponse_1 extends _i1.SmartFake
    implements _i3.MealsByCategoryResponse {
  _FakeMealsByCategoryResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsApiClient extends _i1.Mock implements _i4.MealsApiClient {
  MockMealsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.MealCategoriesReponse> getMealsCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getMealsCategories, []),
            returnValue: _i5.Future<_i2.MealCategoriesReponse>.value(
              _FakeMealCategoriesReponse_0(
                this,
                Invocation.method(#getMealsCategories, []),
              ),
            ),
          )
          as _i5.Future<_i2.MealCategoriesReponse>);

  @override
  _i5.Future<_i3.MealsByCategoryResponse> getMealsByCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsByCategory, [category]),
            returnValue: _i5.Future<_i3.MealsByCategoryResponse>.value(
              _FakeMealsByCategoryResponse_1(
                this,
                Invocation.method(#getMealsByCategory, [category]),
              ),
            ),
          )
          as _i5.Future<_i3.MealsByCategoryResponse>);
}
