// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/Exercise/data/repository_imp/exercise_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/features/Exercise/data/data_source/exercise_remote_data_source.dart'
    as _i3;
import 'package:fitness_app/features/Exercise/data/model/difficult_level_dto.dart'
    as _i5;
import 'package:fitness_app/features/Exercise/data/model/exercise_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExerciseResponseDTO_0 extends _i1.SmartFake
    implements _i2.ExerciseResponseDTO {
  _FakeExerciseResponseDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRemoteDataSource extends _i1.Mock
    implements _i3.ExerciseRemoteDataSource {
  MockExerciseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExerciseResponseDTO> getExercises(
    String? muscleId,
    String? difficultyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercises, [muscleId, difficultyId]),
            returnValue: _i4.Future<_i2.ExerciseResponseDTO>.value(
              _FakeExerciseResponseDTO_0(
                this,
                Invocation.method(#getExercises, [muscleId, difficultyId]),
              ),
            ),
          )
          as _i4.Future<_i2.ExerciseResponseDTO>);

  @override
  _i4.Future<List<_i5.DifficultyLevelDTO>> getLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getLevels, []),
            returnValue: _i4.Future<List<_i5.DifficultyLevelDTO>>.value(
              <_i5.DifficultyLevelDTO>[],
            ),
          )
          as _i4.Future<List<_i5.DifficultyLevelDTO>>);
}
